gem 'capistrano',  '~> 3.2', :github => 'capistrano/capistrano'
gem 'capistrano-file-permissions', '~> 0.1.0', :github => 'capistrano/file-permissions'
gem 'capistrano-composer', '~> 0.0.4', :github => 'capistrano/composer'
gem 'capistrano-symfony', '~> 0.2', :github => 'capistrano/symfony'
gem 'capistrano-grunt', '~> 0.0.4', :github => 'roots/capistrano-grunt'
gem 'capistrano-bower', '~> 1.1.0', :github => 'platanus/capistrano-bower'
gem 'capistrano-npm', '~> 1.0.1', :github => 'capistrano/npm'