+function(b){b.fn.emulateTransitionEnd=function(d){var a=!1,c=this;b(this).one(b.support.transition.end,function(){a=!0});setTimeout(function(){a||b(c).trigger(b.support.transition.end)},d);return this};b(function(){var d=b.support,a;a:{a=document.createElement("bootstrap");var c={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},e;for(e in c)if(void 0!==a.style[e]){a={end:c[e]};break a}a=void 0}d.transition=
a})}(jQuery);

+function(a){var g=function(b){a(b).on("click",'[data-dismiss="alert"]',this.close)};g.prototype.close=function(b){function e(){d.trigger("closed.bs.alert").remove()}var c=a(this),f=c.attr("data-target");f||(f=(f=c.attr("href"))&&f.replace(/.*(?=#[^\s]*$)/,""));var d=a(f);b&&b.preventDefault();d.length||(d=c.hasClass("alert")?c:c.parent());d.trigger(b=a.Event("close.bs.alert"));b.isDefaultPrevented()||(d.removeClass("in"),a.support.transition&&d.hasClass("fade")?d.one(a.support.transition.end,e).emulateTransitionEnd(150):
e())};var h=a.fn.alert;a.fn.alert=function(b){return this.each(function(){var e=a(this),c=e.data("bs.alert");c||e.data("bs.alert",c=new g(this));"string"==typeof b&&c[b].call(e)})};a.fn.alert.Constructor=g;a.fn.alert.noConflict=function(){a.fn.alert=h;return this};a(document).on("click.bs.alert.data-api",'[data-dismiss="alert"]',g.prototype.close)}(jQuery);

+function(c){var e=function(b,a){this.$element=c(b);this.options=c.extend({},e.DEFAULTS,a)};e.DEFAULTS={loadingText:"loading..."};e.prototype.setState=function(b){var a=this.$element,d=a.is("input")?"val":"html",c=a.data();b+="Text";c.resetText||a.data("resetText",a[d]());a[d](c[b]||this.options[b]);setTimeout(function(){"loadingText"==b?a.addClass("disabled").attr("disabled","disabled"):a.removeClass("disabled").removeAttr("disabled")},0)};e.prototype.toggle=function(){var b=this.$element.closest('[data-toggle="buttons"]'),
a=!0;if(b.length){var c=this.$element.find("input");"radio"===c.prop("type")&&(c.prop("checked")&&this.$element.hasClass("active")?a=!1:b.find(".active").removeClass("active"));a&&c.prop("checked",!this.$element.hasClass("active")).trigger("change")}a&&this.$element.toggleClass("active")};var f=c.fn.button;c.fn.button=function(b){return this.each(function(){var a=c(this),d=a.data("bs.button"),f="object"==typeof b&&b;d||a.data("bs.button",d=new e(this,f));"toggle"==b?d.toggle():b&&d.setState(b)})};
c.fn.button.Constructor=e;c.fn.button.noConflict=function(){c.fn.button=f;return this};c(document).on("click.bs.button.data-api","[data-toggle^=button]",function(b){var a=c(b.target);a.hasClass("btn")||(a=a.closest(".btn"));a.button("toggle");b.preventDefault()})}(jQuery);

+function(b){var d=function(a,f){this.$element=b(a);this.$indicators=this.$element.find(".carousel-indicators");this.options=f;this.paused=this.sliding=this.interval=this.$active=this.$items=null;"hover"==this.options.pause&&this.$element.on("mouseenter",b.proxy(this.pause,this)).on("mouseleave",b.proxy(this.cycle,this))};d.DEFAULTS={interval:5E3,pause:"hover",wrap:!0};d.prototype.cycle=function(a){a||(this.paused=!1);this.interval&&clearInterval(this.interval);this.options.interval&&!this.paused&&
(this.interval=setInterval(b.proxy(this.next,this),this.options.interval));return this};d.prototype.getActiveIndex=function(){this.$active=this.$element.find(".item.active");this.$items=this.$active.parent().children();return this.$items.index(this.$active)};d.prototype.to=function(a){var f=this,c=this.getActiveIndex();if(!(a>this.$items.length-1||0>a))return this.sliding?this.$element.one("slid.bs.carousel",function(){f.to(a)}):c==a?this.pause().cycle():this.slide(a>c?"next":"prev",b(this.$items[a]))};
d.prototype.pause=function(a){a||(this.paused=!0);this.$element.find(".next, .prev").length&&b.support.transition.end&&(this.$element.trigger(b.support.transition.end),this.cycle(!0));this.interval=clearInterval(this.interval);return this};d.prototype.next=function(){if(!this.sliding)return this.slide("next")};d.prototype.prev=function(){if(!this.sliding)return this.slide("prev")};d.prototype.slide=function(a,f){var c=this.$element.find(".item.active"),e=f||c[a](),d=this.interval,h="next"==a?"left":
"right",g="next"==a?"first":"last",k=this;if(!e.length){if(!this.options.wrap)return;e=this.$element.find(".item")[g]()}this.sliding=!0;d&&this.pause();g=b.Event("slide.bs.carousel",{relatedTarget:e[0],direction:h});if(!e.hasClass("active")){this.$indicators.length&&(this.$indicators.find(".active").removeClass("active"),this.$element.one("slid.bs.carousel",function(){var a=b(k.$indicators.children()[k.getActiveIndex()]);a&&a.addClass("active")}));if(b.support.transition&&this.$element.hasClass("slide")){this.$element.trigger(g);
if(g.isDefaultPrevented())return;e.addClass(a);e[0].offsetWidth;c.addClass(h);e.addClass(h);c.one(b.support.transition.end,function(){e.removeClass([a,h].join(" ")).addClass("active");c.removeClass(["active",h].join(" "));k.sliding=!1;setTimeout(function(){k.$element.trigger("slid.bs.carousel")},0)}).emulateTransitionEnd(600)}else{this.$element.trigger(g);if(g.isDefaultPrevented())return;c.removeClass("active");e.addClass("active");this.sliding=!1;this.$element.trigger("slid.bs.carousel")}d&&this.cycle();
return this}};var m=b.fn.carousel;b.fn.carousel=function(a){return this.each(function(){var f=b(this),c=f.data("bs.carousel"),e=b.extend({},d.DEFAULTS,f.data(),"object"==typeof a&&a),l="string"==typeof a?a:e.slide;c||f.data("bs.carousel",c=new d(this,e));if("number"==typeof a)c.to(a);else if(l)c[l]();else e.interval&&c.pause().cycle()})};b.fn.carousel.Constructor=d;b.fn.carousel.noConflict=function(){b.fn.carousel=m;return this};b(document).on("click.bs.carousel.data-api","[data-slide], [data-slide-to]",
function(a){var f=b(this),c,e=b(f.attr("data-target")||(c=f.attr("href"))&&c.replace(/.*(?=#[^\s]+$)/,""));c=b.extend({},e.data(),f.data());var d=f.attr("data-slide-to");d&&(c.interval=!1);e.carousel(c);(d=f.attr("data-slide-to"))&&e.data("bs.carousel").to(d);a.preventDefault()});b(window).on("load",function(){b('[data-ride="carousel"]').each(function(){var a=b(this);a.carousel(a.data())})})}(jQuery);

+function(b){var e=function(a,c){this.$element=b(a);this.options=b.extend({},e.DEFAULTS,c);this.transitioning=null;this.options.parent&&(this.$parent=b(this.options.parent));this.options.toggle&&this.toggle()};e.DEFAULTS={toggle:!0};e.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};e.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var a=b.Event("show.bs.collapse");this.$element.trigger(a);if(!a.isDefaultPrevented()){if((a=this.$parent&&
this.$parent.find("> .panel > .in"))&&a.length){var c=a.data("bs.collapse");if(c&&c.transitioning)return;a.collapse("hide");c||a.data("bs.collapse",null)}var d=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[d](0);this.transitioning=1;a=function(){this.$element.removeClass("collapsing").addClass("in")[d]("auto");this.transitioning=0;this.$element.trigger("shown.bs.collapse")};if(!b.support.transition)return a.call(this);c=b.camelCase(["scroll",d].join("-"));this.$element.one(b.support.transition.end,
b.proxy(a,this)).emulateTransitionEnd(350)[d](this.$element[0][c])}}};e.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var a=b.Event("hide.bs.collapse");this.$element.trigger(a);if(!a.isDefaultPrevented()){a=this.dimension();this.$element[a](this.$element[a]())[0].offsetHeight;this.$element.addClass("collapsing").removeClass("collapse").removeClass("in");this.transitioning=1;var c=function(){this.transitioning=0;this.$element.trigger("hidden.bs.collapse").removeClass("collapsing").addClass("collapse")};
if(!b.support.transition)return c.call(this);this.$element[a](0).one(b.support.transition.end,b.proxy(c,this)).emulateTransitionEnd(350)}}};e.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};var h=b.fn.collapse;b.fn.collapse=function(a){return this.each(function(){var c=b(this),d=c.data("bs.collapse"),k=b.extend({},e.DEFAULTS,c.data(),"object"==typeof a&&a);d||c.data("bs.collapse",d=new e(this,k));if("string"==typeof a)d[a]()})};b.fn.collapse.Constructor=e;b.fn.collapse.noConflict=
function(){b.fn.collapse=h;return this};b(document).on("click.bs.collapse.data-api","[data-toggle=collapse]",function(a){var c=b(this),d;a=c.attr("data-target")||a.preventDefault()||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"");d=b(a);var e=(a=d.data("bs.collapse"))?"toggle":c.data(),f=c.attr("data-parent"),g=f&&b(f);a&&a.transitioning||(g&&g.find('[data-toggle=collapse][data-parent="'+f+'"]').not(c).addClass("collapsed"),c[d.hasClass("in")?"addClass":"removeClass"]("collapsed"));d.collapse(e)})}(jQuery);

+function(d){function g(){d(k).remove();d(f).each(function(b){var a=h(d(this));a.hasClass("open")&&(a.trigger(b=d.Event("hide.bs.dropdown")),b.isDefaultPrevented()||a.removeClass("open").trigger("hidden.bs.dropdown"))})}function h(b){var a=b.attr("data-target");a||(a=(a=b.attr("href"))&&/#/.test(a)&&a.replace(/.*(?=#[^\s]*$)/,""));return(a=a&&d(a))&&a.length?a:b.parent()}var k=".dropdown-backdrop",f="[data-toggle=dropdown]",e=function(b){d(b).on("click.bs.dropdown",this.toggle)};e.prototype.toggle=
function(b){var a=d(this);if(!a.is(".disabled, :disabled")){var c=h(a);b=c.hasClass("open");g();if(!b){if("ontouchstart"in document.documentElement&&!c.closest(".navbar-nav").length)d('<div class="dropdown-backdrop"/>').insertAfter(d(this)).on("click",g);c.trigger(b=d.Event("show.bs.dropdown"));if(b.isDefaultPrevented())return;c.toggleClass("open").trigger("shown.bs.dropdown");a.focus()}return!1}};e.prototype.keydown=function(b){if(/(38|40|27)/.test(b.keyCode)){var a=d(this);b.preventDefault();b.stopPropagation();
if(!a.is(".disabled, :disabled")){var c=h(a),e=c.hasClass("open");if(!e||e&&27==b.keyCode)return 27==b.which&&c.find(f).focus(),a.click();a=d("[role=menu] li:not(.divider):visible a",c);a.length&&(c=a.index(a.filter(":focus")),38==b.keyCode&&0<c&&c--,40==b.keyCode&&c<a.length-1&&c++,~c||(c=0),a.eq(c).focus())}}};var l=d.fn.dropdown;d.fn.dropdown=function(b){return this.each(function(){var a=d(this),c=a.data("bs.dropdown");c||a.data("bs.dropdown",c=new e(this));"string"==typeof b&&c[b].call(a)})};
d.fn.dropdown.Constructor=e;d.fn.dropdown.noConflict=function(){d.fn.dropdown=l;return this};d(document).on("click.bs.dropdown.data-api",g).on("click.bs.dropdown.data-api",".dropdown form",function(b){b.stopPropagation()}).on("click.bs.dropdown.data-api",f,e.prototype.toggle).on("keydown.bs.dropdown.data-api",f+", [role=menu]",e.prototype.keydown)}(jQuery);

+function(b){var d=function(a,c){this.options=c;this.$element=b(a);this.$backdrop=this.isShown=null;this.options.remote&&this.$element.load(this.options.remote)};d.DEFAULTS={backdrop:!0,keyboard:!0,show:!0};d.prototype.toggle=function(a){return this[this.isShown?"hide":"show"](a)};d.prototype.show=function(a){var c=this,e=b.Event("show.bs.modal",{relatedTarget:a});this.$element.trigger(e);this.isShown||e.isDefaultPrevented()||(this.isShown=!0,this.escape(),this.$element.on("click.dismiss.modal",'[data-dismiss="modal"]',
b.proxy(this.hide,this)),this.backdrop(function(){var e=b.support.transition&&c.$element.hasClass("fade");c.$element.parent().length||c.$element.appendTo(document.body);c.$element.show();e&&c.$element[0].offsetWidth;c.$element.addClass("in").attr("aria-hidden",!1);c.enforceFocus();var d=b.Event("shown.bs.modal",{relatedTarget:a});e?c.$element.find(".modal-dialog").one(b.support.transition.end,function(){c.$element.focus().trigger(d)}).emulateTransitionEnd(300):c.$element.focus().trigger(d)}))};d.prototype.hide=
function(a){a&&a.preventDefault();a=b.Event("hide.bs.modal");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=!1,this.escape(),b(document).off("focusin.bs.modal"),this.$element.removeClass("in").attr("aria-hidden",!0).off("click.dismiss.modal"),b.support.transition&&this.$element.hasClass("fade")?this.$element.one(b.support.transition.end,b.proxy(this.hideModal,this)).emulateTransitionEnd(300):this.hideModal())};d.prototype.enforceFocus=function(){b(document).off("focusin.bs.modal").on("focusin.bs.modal",
b.proxy(function(a){this.$element[0]===a.target||this.$element.has(a.target).length||this.$element.focus()},this))};d.prototype.escape=function(){if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.bs.modal",b.proxy(function(a){27==a.which&&this.hide()},this));else this.isShown||this.$element.off("keyup.dismiss.bs.modal")};d.prototype.hideModal=function(){var a=this;this.$element.hide();this.backdrop(function(){a.removeBackdrop();a.$element.trigger("hidden.bs.modal")})};d.prototype.removeBackdrop=
function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};d.prototype.backdrop=function(a){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var e=b.support.transition&&c;this.$backdrop=b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);this.$element.on("click.dismiss.modal",b.proxy(function(a){a.target===a.currentTarget&&("static"==this.options.backdrop?this.$element[0].focus.call(this.$element[0]):this.hide.call(this))},this));e&&
this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");a&&(e?this.$backdrop.one(b.support.transition.end,a).emulateTransitionEnd(150):a())}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,a).emulateTransitionEnd(150):a()):a&&a()};var h=b.fn.modal;b.fn.modal=function(a,c){return this.each(function(){var e=b(this),f=e.data("bs.modal"),g=b.extend({},d.DEFAULTS,e.data(),"object"==typeof a&&
a);f||e.data("bs.modal",f=new d(this,g));if("string"==typeof a)f[a](c);else g.show&&f.show(c)})};b.fn.modal.Constructor=d;b.fn.modal.noConflict=function(){b.fn.modal=h;return this};b(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),e=c.attr("href"),d=b(c.attr("data-target")||e&&e.replace(/.*(?=#[^\s]+$)/,"")),e=d.data("modal")?"toggle":b.extend({remote:!/#/.test(e)&&e},d.data(),c.data());a.preventDefault();d.modal(e,this).one("hide",function(){c.is(":visible")&&
c.focus()})});b(document).on("show.bs.modal",".modal",function(){b(document.body).addClass("modal-open")}).on("hidden.bs.modal",".modal",function(){b(document.body).removeClass("modal-open")})}(jQuery);

+function(d){var c=function(a,b){this.type=this.options=this.enabled=this.timeout=this.hoverState=this.$element=null;this.init("tooltip",a,b)};c.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:!1,container:!1};c.prototype.init=function(a,b,e){this.enabled=!0;this.type=a;this.$element=d(b);this.options=this.getOptions(e);a=this.options.trigger.split(" ");
for(b=a.length;b--;)if(e=a[b],"click"==e)this.$element.on("click."+this.type,this.options.selector,d.proxy(this.toggle,this));else if("manual"!=e){var f="hover"==e?"mouseleave":"blur";this.$element.on(("hover"==e?"mouseenter":"focus")+"."+this.type,this.options.selector,d.proxy(this.enter,this));this.$element.on(f+"."+this.type,this.options.selector,d.proxy(this.leave,this))}this.options.selector?this._options=d.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};c.prototype.getDefaults=
function(){return c.DEFAULTS};c.prototype.getOptions=function(a){a=d.extend({},this.getDefaults(),this.$element.data(),a);a.delay&&"number"==typeof a.delay&&(a.delay={show:a.delay,hide:a.delay});return a};c.prototype.getDelegateOptions=function(){var a={},b=this.getDefaults();this._options&&d.each(this._options,function(e,f){b[e]!=f&&(a[e]=f)});return a};c.prototype.enter=function(a){var b=a instanceof this.constructor?a:d(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type);
clearTimeout(b.timeout);b.hoverState="in";if(!b.options.delay||!b.options.delay.show)return b.show();b.timeout=setTimeout(function(){"in"==b.hoverState&&b.show()},b.options.delay.show)};c.prototype.leave=function(a){var b=a instanceof this.constructor?a:d(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type);clearTimeout(b.timeout);b.hoverState="out";if(!b.options.delay||!b.options.delay.hide)return b.hide();b.timeout=setTimeout(function(){"out"==b.hoverState&&b.hide()},b.options.delay.hide)};
c.prototype.show=function(){var a=d.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled&&(this.$element.trigger(a),!a.isDefaultPrevented())){var b=this.tip();this.setContent();this.options.animation&&b.addClass("fade");var a="function"==typeof this.options.placement?this.options.placement.call(this,b[0],this.$element[0]):this.options.placement,e=/\s?auto?\s?/i,f=e.test(a);f&&(a=a.replace(e,"")||"top");b.detach().css({top:0,left:0,display:"block"}).addClass(a);this.options.container?b.appendTo(this.options.container):
b.insertAfter(this.$element);var e=this.getPosition(),c=b[0].offsetWidth,k=b[0].offsetHeight;if(f){var g=this.$element.parent(),f=a,h=document.documentElement.scrollTop||document.body.scrollTop,l="body"==this.options.container?window.innerWidth:g.outerWidth(),m="body"==this.options.container?window.innerHeight:g.outerHeight(),g="body"==this.options.container?0:g.offset().left,a="bottom"==a&&e.top+e.height+k-h>m?"top":"top"==a&&0>e.top-h-k?"bottom":"right"==a&&e.right+c>l?"left":"left"==a&&e.left-
c<g?"right":a;b.removeClass(f).addClass(a)}b=this.getCalculatedOffset(a,e,c,k);this.applyPlacement(b,a);this.$element.trigger("shown.bs."+this.type)}};c.prototype.applyPlacement=function(a,b){var e,c=this.tip(),d=c[0].offsetWidth,k=c[0].offsetHeight,g=parseInt(c.css("margin-top"),10),h=parseInt(c.css("margin-left"),10);isNaN(g)&&(g=0);isNaN(h)&&(h=0);a.top+=g;a.left+=h;c.offset(a).addClass("in");g=c[0].offsetWidth;h=c[0].offsetHeight;"top"==b&&h!=k&&(e=!0,a.top=a.top+k-h);/bottom|top/.test(b)?(k=
0,0>a.left&&(k=-2*a.left,a.left=0,c.offset(a),g=c[0].offsetWidth),this.replaceArrow(k-d+g,g,"left")):this.replaceArrow(h-k,h,"top");e&&c.offset(a)};c.prototype.replaceArrow=function(a,b,c){this.arrow().css(c,a?50*(1-a/b)+"%":"")};c.prototype.setContent=function(){var a=this.tip(),b=this.getTitle();a.find(".tooltip-inner")[this.options.html?"html":"text"](b);a.removeClass("fade in top bottom left right")};c.prototype.hide=function(){function a(){"in"!=b.hoverState&&c.detach()}var b=this,c=this.tip(),
f=d.Event("hide.bs."+this.type);this.$element.trigger(f);if(!f.isDefaultPrevented())return c.removeClass("in"),d.support.transition&&this.$tip.hasClass("fade")?c.one(d.support.transition.end,a).emulateTransitionEnd(150):a(),this.$element.trigger("hidden.bs."+this.type),this};c.prototype.fixTitle=function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||"").attr("title","")};c.prototype.hasContent=function(){return this.getTitle()};
c.prototype.getPosition=function(){var a=this.$element[0];return d.extend({},"function"==typeof a.getBoundingClientRect?a.getBoundingClientRect():{width:a.offsetWidth,height:a.offsetHeight},this.$element.offset())};c.prototype.getCalculatedOffset=function(a,b,c,d){return"bottom"==a?{top:b.top+b.height,left:b.left+b.width/2-c/2}:"top"==a?{top:b.top-d,left:b.left+b.width/2-c/2}:"left"==a?{top:b.top+b.height/2-d/2,left:b.left-c}:{top:b.top+b.height/2-d/2,left:b.left+b.width}};c.prototype.getTitle=function(){var a=
this.$element,b=this.options;return a.attr("data-original-title")||("function"==typeof b.title?b.title.call(a[0]):b.title)};c.prototype.tip=function(){return this.$tip=this.$tip||d(this.options.template)};c.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};c.prototype.validate=function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)};c.prototype.enable=function(){this.enabled=!0};c.prototype.disable=function(){this.enabled=!1};
c.prototype.toggleEnabled=function(){this.enabled=!this.enabled};c.prototype.toggle=function(a){a=a?d(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type):this;a.tip().hasClass("in")?a.leave(a):a.enter(a)};c.prototype.destroy=function(){this.hide().$element.off("."+this.type).removeData("bs."+this.type)};var l=d.fn.tooltip;d.fn.tooltip=function(a){return this.each(function(){var b=d(this),e=b.data("bs.tooltip"),f="object"==typeof a&&a;e||b.data("bs.tooltip",e=new c(this,f));
if("string"==typeof a)e[a]()})};d.fn.tooltip.Constructor=c;d.fn.tooltip.noConflict=function(){d.fn.tooltip=l;return this}}(jQuery);

+function(b){var a=function(c,a){this.init("popover",c,a)};if(!b.fn.tooltip)throw Error("Popover requires tooltip.js");a.DEFAULTS=b.extend({},b.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});a.prototype=b.extend({},b.fn.tooltip.Constructor.prototype);a.prototype.constructor=a;a.prototype.getDefaults=function(){return a.DEFAULTS};a.prototype.setContent=
function(){var a=this.tip(),b=this.getTitle(),d=this.getContent();a.find(".popover-title")[this.options.html?"html":"text"](b);a.find(".popover-content")[this.options.html?"html":"text"](d);a.removeClass("fade top bottom left right in");a.find(".popover-title").html()||a.find(".popover-title").hide()};a.prototype.hasContent=function(){return this.getTitle()||this.getContent()};a.prototype.getContent=function(){var a=this.$element,b=this.options;return a.attr("data-content")||("function"==typeof b.content?
b.content.call(a[0]):b.content)};a.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};a.prototype.tip=function(){this.$tip||(this.$tip=b(this.options.template));return this.$tip};var e=b.fn.popover;b.fn.popover=function(c){return this.each(function(){var f=b(this),d=f.data("bs.popover"),e="object"==typeof c&&c;d||f.data("bs.popover",d=new a(this,e));if("string"==typeof c)d[c]()})};b.fn.popover.Constructor=a;b.fn.popover.noConflict=function(){b.fn.popover=e;return this}}(jQuery);

+function(a){function e(b,f){var c,d=a.proxy(this.process,this);this.$element=a(b).is("body")?a(window):a(b);this.$body=a("body");this.$scrollElement=this.$element.on("scroll.bs.scroll-spy.data-api",d);this.options=a.extend({},e.DEFAULTS,f);this.selector=(this.options.target||(c=a(b).attr("href"))&&c.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.offsets=a([]);this.targets=a([]);this.activeTarget=null;this.refresh();this.process()}e.DEFAULTS={offset:10};e.prototype.refresh=function(){var b=
this.$element[0]==window?"offset":"position";this.offsets=a([]);this.targets=a([]);var f=this;this.$body.find(this.selector).map(function(){var c=a(this),c=c.data("target")||c.attr("href"),d=/^#\w/.test(c)&&a(c);return d&&d.length&&[[d[b]().top+(!a.isWindow(f.$scrollElement.get(0))&&f.$scrollElement.scrollTop()),c]]||null}).sort(function(b,a){return b[0]-a[0]}).each(function(){f.offsets.push(this[0]);f.targets.push(this[1])})};e.prototype.process=function(){var b=this.$scrollElement.scrollTop()+this.options.offset,
a=(this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight)-this.$scrollElement.height(),c=this.offsets,d=this.targets,e=this.activeTarget,g;if(b>=a)return e!=(g=d.last()[0])&&this.activate(g);for(g=c.length;g--;)e!=d[g]&&b>=c[g]&&(!c[g+1]||b<=c[g+1])&&this.activate(d[g])};e.prototype.activate=function(b){this.activeTarget=b;a(this.selector).parents(".active").removeClass("active");b=a(this.selector+'[data-target="'+b+'"],'+this.selector+'[href="'+b+'"]').parents("li").addClass("active");
b.parent(".dropdown-menu").length&&(b=b.closest("li.dropdown").addClass("active"));b.trigger("activate.bs.scrollspy")};var h=a.fn.scrollspy;a.fn.scrollspy=function(b){return this.each(function(){var f=a(this),c=f.data("bs.scrollspy"),d="object"==typeof b&&b;c||f.data("bs.scrollspy",c=new e(this,d));if("string"==typeof b)c[b]()})};a.fn.scrollspy.Constructor=e;a.fn.scrollspy.noConflict=function(){a.fn.scrollspy=h;return this};a(window).on("load",function(){a('[data-spy="scroll"]').each(function(){var b=
a(this);b.scrollspy(b.data())})})}(jQuery);

+function(c){var d=function(a){this.element=c(a)};d.prototype.show=function(){var a=this.element,e=a.closest("ul:not(.dropdown-menu)"),b=a.data("target");b||(b=(b=a.attr("href"))&&b.replace(/.*(?=#[^\s]*$)/,""));if(!a.parent("li").hasClass("active")){var g=e.find(".active:last a")[0],f=c.Event("show.bs.tab",{relatedTarget:g});a.trigger(f);f.isDefaultPrevented()||(b=c(b),this.activate(a.parent("li"),e),this.activate(b,b.parent(),function(){a.trigger({type:"shown.bs.tab",relatedTarget:g})}))}};d.prototype.activate=
function(a,e,b){function g(){f.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");d?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");b&&b()}var f=e.find("> .active"),d=b&&c.support.transition&&f.hasClass("fade");d?f.one(c.support.transition.end,g).emulateTransitionEnd(150):g();f.removeClass("in")};var h=c.fn.tab;c.fn.tab=function(a){return this.each(function(){var e=c(this),
b=e.data("bs.tab");b||e.data("bs.tab",b=new d(this));if("string"==typeof a)b[a]()})};c.fn.tab.Constructor=d;c.fn.tab.noConflict=function(){c.fn.tab=h;return this};c(document).on("click.bs.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();c(this).tab("show")})}(jQuery);

+function(c){var d=function(a,b){this.options=c.extend({},d.DEFAULTS,b);this.$window=c(window).on("scroll.bs.affix.data-api",c.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",c.proxy(this.checkPositionWithEventLoop,this));this.$element=c(a);this.affixed=this.unpin=null;this.checkPosition()};d.RESET="affix affix-top affix-bottom";d.DEFAULTS={offset:0};d.prototype.checkPositionWithEventLoop=function(){setTimeout(c.proxy(this.checkPosition,this),1)};d.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=
c(document).height(),b=this.$window.scrollTop(),f=this.$element.offset(),e=this.options.offset,h=e.top,g=e.bottom;"object"!=typeof e&&(g=h=e);"function"==typeof h&&(h=e.top());"function"==typeof g&&(g=e.bottom());a=null!=this.unpin&&b+this.unpin<=f.top?!1:null!=g&&f.top+this.$element.height()>=a-g?"bottom":null!=h&&b<=h?"top":!1;this.affixed!==a&&(this.unpin&&this.$element.css("top",""),this.affixed=a,this.unpin="bottom"==a?f.top-b:null,this.$element.removeClass(d.RESET).addClass("affix"+(a?"-"+a:
"")),"bottom"==a&&this.$element.offset({top:document.body.offsetHeight-g-this.$element.height()}))}};var k=c.fn.affix;c.fn.affix=function(a){return this.each(function(){var b=c(this),f=b.data("bs.affix"),e="object"==typeof a&&a;f||b.data("bs.affix",f=new d(this,e));if("string"==typeof a)f[a]()})};c.fn.affix.Constructor=d;c.fn.affix.noConflict=function(){c.fn.affix=k;return this};c(window).on("load",function(){c('[data-spy="affix"]').each(function(){var a=c(this),b=a.data();b.offset=b.offset||{};b.offsetBottom&&
(b.offset.bottom=b.offsetBottom);b.offsetTop&&(b.offset.top=b.offsetTop);a.affix(b)})})}(jQuery);

!function(a){var f=function(c){a(c).on("click",'[data-addfield="collection"]',this.addField)},g=function(c){a(c).on("click",'[data-removefield="collection"]',this.removeField)};f.prototype.addField=function(c){var b=a(this),d=b.attr("data-collection"),b=b.attr("data-prototype-name");c&&c.preventDefault();var e=a("#"+d);c=e.find("> ul");for(var d=c.find("li").size(),e=e.attr("data-prototype"),f=e.match(/id="(.*?)"/),b=RegExp(b,"g");0<a("#"+f[1].replace(b,d)).size();)d++;e=e.replace(b,d);e=e.replace(/__id__/g,
f[1].replace(b,d));a("<li></li>").html(e).appendTo(c)};g.prototype.removeField=function(c){var b=a(this);b.attr("data-field");c&&c.preventDefault();b.closest("li").remove()};var h=a.fn.addField,k=a.fn.removeField;a.fn.addField=function(c){return this.each(function(){var b=a(this),d=b.data("addfield");d||b.data("addfield",d=new f(this));"string"==typeof c&&d[c].call(b)})};a.fn.removeField=function(c){return this.each(function(){var b=a(this),d=b.data("removefield");d||b.data("removefield",d=new g(this));
"string"==typeof c&&d[c].call(b)})};a.fn.addField.Constructor=f;a.fn.removeField.Constructor=g;a.fn.addField.noConflict=function(){a.fn.addField=h;return this};a.fn.removeField.noConflict=function(){a.fn.removeField=k;return this};a(document).on("click.addfield.data-api",'[data-addfield="collection"]',f.prototype.addField);a(document).on("click.removefield.data-api",'[data-removefield="collection"]',g.prototype.removeField)}(window.jQuery);

!function(a){var f=function(c){a(c).on("click",'[data-addfield="collection"]',this.addField)},g=function(c){a(c).on("click",'[data-removefield="collection"]',this.removeField)};f.prototype.addField=function(c){var b=a(this),d=b.attr("data-collection"),b=b.attr("data-prototype-name");c&&c.preventDefault();var e=a("#"+d);c=e.find("> ul");for(var d=c.find("li").size(),e=e.attr("data-prototype"),f=e.match(/id="(.*?)"/),b=RegExp(b,"g");0<a("#"+f[1].replace(b,d)).size();)d++;e=e.replace(b,d);e=e.replace(/__id__/g,
f[1].replace(b,d));a("<li></li>").html(e).appendTo(c)};g.prototype.removeField=function(c){var b=a(this);b.attr("data-field");c&&c.preventDefault();b.closest("li").remove()};var h=a.fn.addField,k=a.fn.removeField;a.fn.addField=function(c){return this.each(function(){var b=a(this),d=b.data("addfield");d||b.data("addfield",d=new f(this));"string"==typeof c&&d[c].call(b)})};a.fn.removeField=function(c){return this.each(function(){var b=a(this),d=b.data("removefield");d||b.data("removefield",d=new g(this));
"string"==typeof c&&d[c].call(b)})};a.fn.addField.Constructor=f;a.fn.removeField.Constructor=g;a.fn.addField.noConflict=function(){a.fn.addField=h;return this};a.fn.removeField.noConflict=function(){a.fn.removeField=k;return this};a(document).on("click.addfield.data-api",'[data-addfield="collection"]',f.prototype.addField);a(document).on("click.removefield.data-api",'[data-removefield="collection"]',g.prototype.removeField)}(window.jQuery);
